version: "3"

vars:
  LOCALSTACK_URL: http://localhost:4566

tasks:
  up:
    desc: Start Localstack
    cmds:
      - docker compose -f localstack/docker-compose.yml up -d

  down:
    desc: Stop Localstack
    cmds:
      - docker compose -f localstack/docker-compose.yml down

  status:
    desc: Localstack health
    cmds:
      - curl {{.LOCALSTACK_URL}}/_localstack/health | jq
